### ISSUE TITLE
Attempt to launch processphoto.py file, Getting AttributeError

### ISSUE THREAD

**Issue by dan79cheg** [no-one2k/unsupervised_stamp_detection#1]
Hello!
I am trying to launch your `processphoto.py` file, it's not working due to this error:
```python
PS C:\Users\Documents\ML\stamp_test> & C:/Users/AppData/Local/Programs/Python/Python37/python.exe c:/Users/Documents/ML/stamp_test/processphoto.py
C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\cluster\_kmeans.py:793: FutureWarning: 'n_jobs' was deprecated in version 0.23 and will be removed in 1.0 (renaming of 0.25).
  " removed in 1.0 (renaming of 0.25).", FutureWarning)
Traceback (most recent call last):
  File "c:/Users/Documents/ML/stamp_test/processphoto.py", line 170, in <module>
    process_file('in.png', 'out.png', 'xx')
  File "c:/Users/Documents/ML/stamp_test/processphoto.py", line 160, in process_file
    ctrs = get_contours(image)
  File "c:/Users/Documents/ML/stamp_test/processphoto.py", line 80, in get_contours
    (image_cntr, ctrs_clust, hiers) = cv2.findContours(closing, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)
```

Here is the code where the erroroccured:

```python
    for cluster in clusters:
        # detect edges
        edged = cv2.Canny(cluster, 10, 250)
        make_border(edged)                           # <====== line 80

        # dilate = make objects thicker
        kernel_size = max(image.shape) // 50
        kernel = np.ones((kernel_size, kernel_size), np.uint8)
```

What can you recommend me to do? What can work best to make that model work?
Appreciate any help! 
Thanks!

Also getting this issue on another attempt...
```python
Traceback (most recent call last):
  File "c:/Users/Documents/ML/stamp_test/processphoto.py", line 191, in <module>
    process_file('in.png', 'out.png', 'xx')
  File "c:/Users/Documents/ML/stamp_test/processphoto.py", line 180, in process_file
    ctrs, image, min_pct=0.001, max_pct=0.7)
  File "c:/Users/Documents/ML/stamp_test/processphoto.py", line 111, in filter_contours_by_square
    for ctrs_list in contours
  File "c:/Users/Documents/ML/stamp_test/processphoto.py", line 111, in <listcomp>
    for ctrs_list in contours
  File "c:/Users/Documents/ML/stamp_test/processphoto.py", line 110, in <listcomp>
    get_square(ctr) >= min_square]
  File "c:/Users/Documents/ML/stamp_test/processphoto.py", line 100, in get_square
    h, w = cv2.boundingRect(ctr)[2:4]
cv2.error: OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-dn5w5exm\opencv\modules\imgproc\src\shapedescr.cpp:874: error: (-215:Assertion failed) npoints >= 0 && (depth == CV_32F || depth == CV_32S) in function 'cv::pointSetBoundingRect'
```

Here is the same problem with terminal input:
```python
PS C:\Users\Documents\ML\stamp_test> python processphoto.py -i in.png -o out.png -d xx
C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\cluster\_kmeans.py:793: FutureWarning: 'n_jobs' was deprecated in version 0.23 and will be removed in 1.0 (renaming of 0.25).
  " removed in 1.0 (renaming of 0.25).", FutureWarning)
Traceback (most recent call last):
  File "processphoto.py", line 191, in <module>
    main(sys.argv[1:])
  File "processphoto.py", line 188, in main
    process_file(input_file, result_file, result_dir)
  File "processphoto.py", line 159, in process_file
    ctrs = get_contours(image)
  File "processphoto.py", line 79, in get_contours
    (image_cntr, ctrs_clust, hiers) = cv2.findContours(closing, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)
PS C:\Users\Documents\ML\stamp_test> 
```

**Comment by jigsawcoder** [comment]
> Hello! I am trying to launch your `processphoto.py` file, it's not working due to this error:
> 
> ```python
> PS C:\Users\Documents\ML\stamp_test> & C:/Users/AppData/Local/Programs/Python/Python37/python.exe c:/Users/Documents/ML/stamp_test/processphoto.py
> C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\cluster\_kmeans.py:793: FutureWarning: 'n_jobs' was deprecated in version 0.23 and will be removed in 1.0 (renaming of 0.25).
>   " removed in 1.0 (renaming of 0.25).", FutureWarning)
> Traceback (most recent call last):
>   File "c:/Users/Documents/ML/stamp_test/processphoto.py", line 170, in <module>
>     process_file('in.png', 'out.png', 'xx')
>   File "c:/Users/Documents/ML/stamp_test/processphoto.py", line 160, in process_file
>     ctrs = get_contours(image)
>   File "c:/Users/Documents/ML/stamp_test/processphoto.py", line 80, in get_contours
>     (image_cntr, ctrs_clust, hiers) = cv2.findContours(closing, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
> ValueError: not enough values to unpack (expected 3, got 2)
> ```
> 
> Here is the code where the erroroccured:
> 
> ```python
>     for cluster in clusters:
>         # detect edges
>         edged = cv2.Canny(cluster, 10, 250)
>         make_border(edged)                           # <====== line 80
> 
>         # dilate = make objects thicker
>         kernel_size = max(image.shape) // 50
>         kernel = np.ones((kernel_size, kernel_size), np.uint8)
> ```
> 
> What can you recommend me to do? What can work best to make that model work? Appreciate any help! Thanks!
> 
> Also getting this issue on another attempt...
> 
> ```python
> Traceback (most recent call last):
>   File "c:/Users/Documents/ML/stamp_test/processphoto.py", line 191, in <module>
>     process_file('in.png', 'out.png', 'xx')
>   File "c:/Users/Documents/ML/stamp_test/processphoto.py", line 180, in process_file
>     ctrs, image, min_pct=0.001, max_pct=0.7)
>   File "c:/Users/Documents/ML/stamp_test/processphoto.py", line 111, in filter_contours_by_square
>     for ctrs_list in contours
>   File "c:/Users/Documents/ML/stamp_test/processphoto.py", line 111, in <listcomp>
>     for ctrs_list in contours
>   File "c:/Users/Documents/ML/stamp_test/processphoto.py", line 110, in <listcomp>
>     get_square(ctr) >= min_square]
>   File "c:/Users/Documents/ML/stamp_test/processphoto.py", line 100, in get_square
>     h, w = cv2.boundingRect(ctr)[2:4]
> cv2.error: OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-dn5w5exm\opencv\modules\imgproc\src\shapedescr.cpp:874: error: (-215:Assertion failed) npoints >= 0 && (depth == CV_32F || depth == CV_32S) in function 'cv::pointSetBoundingRect'
> ```
> 
> Here is the same problem with terminal input:
> 
> ```python
> PS C:\Users\Documents\ML\stamp_test> python processphoto.py -i in.png -o out.png -d xx
> C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\cluster\_kmeans.py:793: FutureWarning: 'n_jobs' was deprecated in version 0.23 and will be removed in 1.0 (renaming of 0.25).
>   " removed in 1.0 (renaming of 0.25).", FutureWarning)
> Traceback (most recent call last):
>   File "processphoto.py", line 191, in <module>
>     main(sys.argv[1:])
>   File "processphoto.py", line 188, in main
>     process_file(input_file, result_file, result_dir)
>   File "processphoto.py", line 159, in process_file
>     ctrs = get_contours(image)
>   File "processphoto.py", line 79, in get_contours
>     (image_cntr, ctrs_clust, hiers) = cv2.findContours(closing, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
> ValueError: not enough values to unpack (expected 3, got 2)
> PS C:\Users\Documents\ML\stamp_test> 
> ```

In line 77,
change (image_cntr, ctrs_clust, hiers) to (ctrs_clust, hiers).
Explanation,
cv2.findContours returns only two parameters that are contours, hierarchy.
